import { useState } from 'react';
import { Link } from 'react-router-dom';
import Icon from '../components/Icon';
import { Button, Container } from '../components/ui';
import { adminCatalogApi } from '../lib/api';

export default function AdminCatalogImport() {
  const [file,setFile]=useState(null),[token,setToken]=useState(''),[result,setResult]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  const submit=async(e)=>{e.preventDefault();if(!file||!token){setError('Choose an XLSX workbook and provide an ADMIN access token.');return;}setLoading(true);setError('');try{setResult(await adminCatalogApi.importWorkbook(file,token));}catch(err){setError(err.message);}finally{setLoading(false);}};
  return <Container className="py-10"><nav className="mb-6 flex items-center gap-1.5 text-[12.5px] text-ink-50"><Link to="/">Home</Link><Icon name="chevronRight" size={13}/><span className="font-semibold text-ink">Admin catalogue import</span></nav><div className="mx-auto max-w-2xl rounded-xl border border-line bg-white p-7"><p className="eyebrow">Admin only</p><h1 className="mt-2 text-[28px]">Import product workbook</h1><p className="mt-3 text-[14px] leading-relaxed text-ink-50">SKU metadata is upserted from an XLSX file. Rows without price or quantity remain drafts and cannot be sold.</p><form onSubmit={submit} className="mt-7 space-y-5"><label className="block"><span className="mb-2 block text-[13px] font-semibold">Workbook (.xlsx)</span><input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(e)=>setFile(e.target.files?.[0]??null)} className="block w-full rounded-md border border-line p-3 text-[13px]"/></label><label className="block"><span className="mb-2 block text-[13px] font-semibold">ADMIN access token</span><input type="password" value={token} onChange={(e)=>setToken(e.target.value)} autoComplete="off" placeholder="Paste current session token" className="h-11 w-full rounded-md border border-line px-3 text-[13px]"/></label>{error&&<p role="alert" className="rounded-md bg-clay-50 p-3 text-[13px] text-clay-600">{error}</p>}<Button type="submit" disabled={loading} icon="package">{loading?'Importing…':'Import workbook'}</Button></form>{result&&<div className="mt-7 rounded-lg bg-emerald-50 p-5"><h2 className="text-[16px]">Import complete</h2><p className="mt-2 text-[13px] text-ink-70">Created {result.created}, updated {result.updated}, skipped {result.skipped}.</p>{result.errors?.length>0&&<ul className="mt-3 list-disc pl-5 text-[12px] text-ink-50">{result.errors.map((item)=><li key={item}>{item}</li>)}</ul>}</div>}</div></Container>;
}
